name: Create Release
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'MasUtils.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.toml *.md LICENSE'
    - name: Upload ZIP as a release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./MasUtils.zip
        asset_name: MasUtils.zip
        asset_content_type: application/zip
